```{r results=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,message=FALSE, cache=FALSE)
```

```{r eval='TRUE', echo=FALSE, results='asis'}
if(tableNum ==0) cat('\n'); 
```


```{r, echo=FALSE,results='asis'}
## ----UI
table_id <- paste0('sumtable_', c, '_', ct, '_', cl) # Dynamic outputID

rHandsontableOutput(outputId = table_id)
actionButton("saveBtn", "Save Change")

```

```{r, context="server"}
# Declare outputID: server sometimes doesn't inherit variable from previous environment...
table_id <- paste0('sumtable_', c, '_', ct, '_', cl)
output[[table_id]] <- renderRHandsontable({

  data <- filter(diamonds, color == c,
                 cut == this_cut,
                 clarity == this_clarity) %>%
    as.data.frame()

  rhandsontable(data)
})


# fname <- paste0('./input/cache/outliers/edited_diamond') # R object data frame stored as ASCII text
# values <- list() 
# setHot <- function(x) values[[table_id]] <<- x 

# observeEvent( 
#     input$saveBtn, 
#     {if (!is.null(values[[table_id]])) { # if there's a table input
#       write.csv(values[[table_id]], fname) # overwrite the temporary database file
#       write.csv(x = values[[table_id]], file = paste0(fname, ".csv"), row.names = FALSE) # overwrite
#     }
#   })
#   
#   output[[table_id]] <- renderRHandsontable({ 
#     if (!is.null(input[[table_id]])) { # if there is an rhot user input...
#       DF <- hot_to_r(input[[table_id]]) # convert rhandsontable data to R object and store in data frame
#       setHot(DF) # set the rhandsontable values
#       
#     } else {
#       data <-subset(diamonds, color == c) %>%
#       filter(cut == this_cut) %>%
#       as.data.frame()
#       
#       DF <- readRDS(paste0('./input/cache/diamond/',c ,'_', this_cut,'.RDS')) 
#       
#       setHot(DF) # set the rhandsontable values
#     }
#     
#     rhandsontable(DF) %>% 
#       hot_table(highlightCol = TRUE, highlightRow = TRUE) 
#   }
#   )
  
```